name: snykcheck

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  snykcheck:
    permissions:
      contents: read
      security-events: write
    uses: Vaultrix-in/Vaultrix-CI/.github/workflows/snykcheck.yaml@feat/ci-workflows
    with:
      image_name: wallet-service
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NOTIFY_EMAIL_TO: ${{ secrets.NOTIFY_EMAIL_TO }}
