name: sonarcheck

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  sonarcheck:
    permissions:
      contents: read
      security-events: write
    uses: Vaultrix-in/Vaultrix-CI/.github/workflows/sonarcheck.yaml@feat/ci-workflows
    with:
      image_name: wallet-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NOTIFY_EMAIL_TO: ${{ secrets.NOTIFY_EMAIL_TO }}
