name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: read
      security-events: write
    uses: Vaultrix-in/Vaultrix-CI/.github/workflows/parent-ci.yaml@main
    with:
      image_name: wallet-service
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NOTIFY_EMAIL_TO: ${{ secrets.NOTIFY_EMAIL_TO }}
