name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: Vaultrix-in/Vaultrix-CI/.github/workflows/parent-ci.yaml@main
    with:
      image_name: wallet-service
    secrets:
      PAT_TOKEN: $\{{ secrets.GITHUB_TOKEN \}}
